CREATE TABLE C##CAR.SWITCH_STATIONS (
    SWITCH_STATION_ID VARCHAR2(50) PRIMARY KEY,
    STATION_NAME VARCHAR2(50),
    LONGITUDE NUMBER NOT NULL UNIQUE,
    LATITUDE NUMBER NOT NULL UNIQUE,
    FALIURE_STATUS CHAR(1) CHECK (FALIURE_STATUS IN ('y', 'n')),
    BATTERY_CAPACITY INT NOT NULL,
    AVAILABLE_BATTERY_COUNT INT DEFAULT 0
);
CREATE TABLE C##CAR.BATTERY_MODEL (
    BATTERY_MODEL_ID VARCHAR2(50) PRIMARY KEY,
    BATTERY_LIFE FLOAT NOT NULL,
    TOTAL_CAPACITY VARCHAR2(50) NOT NULL
);
CREATE TABLE C##CAR.BATTERY (
    BATTERY_ID VARCHAR2(50) PRIMARY KEY,
    AVAILABLE_STATUS CHAR(1) DEFAULT '0',
    CURRENT_CAPACITY VARCHAR2(4) NOT NULL,
    MANUFACTURING_DATE TIMESTAMP NOT NULL,
    BATTERY_MODEL_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_BATTERY_MODEL FOREIGN KEY (BATTERY_MODEL_ID)
        REFERENCES C##CAR.BATTERY_MODEL (BATTERY_MODEL_ID)
);
CREATE TABLE C##CAR.VEHICLE_PARAMETERS (
    VEHICLE_MODEL VARCHAR2(50) PRIMARY KEY,
    GEAR_TYPE VARCHAR2(50) NOT NULL,
    WARRANTY_PERIOD TIMESTAMP NOT NULL,
    MANUFACTURER VARCHAR2(50) NOT NULL,
    MAX_SPEED NUMBER
);
CREATE TABLE C##CAR.OWNERS (
    OWNER_ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_P VARCHAR2(50) NOT NULL,
    AVATAR BLOB,
    CREATION_TIME TIMESTAMP NOT NULL,
    PHONE_NUMBER VARCHAR2(50) DEFAULT '+86',
    EMAIL VARCHAR2(50) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('f', 'm')),
    BIRTHDAY TIMESTAMP,
    ADDRESS VARCHAR2(255)
);
CREATE TABLE C##CAR.STAFF (
    EMPLOYEE_ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_P VARCHAR2(50) NOT NULL,
    AVATAR BLOB,
    CREATI_TIME TIMESTAMP NOT NULL,
    PHONE_NUMBER VARCHAR2(50) DEFAULT '+86',
    IDENTITY_NUMBER VARCHAR2(50) NOT NULL,
    NAME_P VARCHAR2(50) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('f', 'm')),
    POSITIONS VARCHAR2(50) DEFAULT '-',
    SALARY NUMBER NOT NULL
);
CREATE TABLE C##CAR.ANNOUNCEMENT (
    ANNOUNCEMENT_ID VARCHAR2(50) PRIMARY KEY,
    PUBLISH_TIME TIMESTAMP NOT NULL,
    PUBLISH_POS VARCHAR2(50),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENTS VARCHAR2(255),
    LIKES INT DEFAULT 0,
    VIEW_COUNT INT DEFAULT 0
);
CREATE TABLE C##CAR.BATTERY_SWITCH_STATIONS (
    BATTERY_ID VARCHAR2(50) PRIMARY KEY,
    SWITCH_STATION_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_BATTERY_BATTERY_SWITCH_STATIONS FOREIGN KEY (BATTERY_ID)
        REFERENCES C##CAR.BATTERY (BATTERY_ID),
    CONSTRAINT FK_BATTERY_SWITCH_STATIONS_SWITCH_STATIONS FOREIGN KEY (SWITCH_STATION_ID)
        REFERENCES C##CAR.SWITCH_STATIONS (SWITCH_STATION_ID)
);
CREATE TABLE C##CAR.SWITCH_RECORDS (
    SWITCH_SERVICE_ID VARCHAR2(50) PRIMARY KEY,
    VEHICLE_ID VARCHAR2(50) NOT NULL,
    SWITCH_TIME TIMESTAMP NOT NULL,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    SWAPPED_BATTERY_ID VARCHAR2(50) NOT NULL,
    SWAPPED_OUT_BATTERY_ID VARCHAR2(50) NOT NULL,
    EVALUATIONS VARCHAR2(255),
    CONSTRAINT FK_SWITCH_RECORDS_VEHICLES FOREIGN KEY (VEHICLE_ID)
        REFERENCES C##CAR.VEHICLES (VEHICLE_ID),
    CONSTRAINT FK_SWITCH_RECORDS_STAFF FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES C##CAR.STAFF (EMPLOYEE_ID),
    CONSTRAINT FK_SWITCH_RECORDS_BATTERY_IN FOREIGN KEY (SWAPPED_BATTERY_ID)
        REFERENCES C##CAR.BATTERY (BATTERY_ID),
    CONSTRAINT FK_SWITCH_RECORDS_BATTERY_OUT FOREIGN KEY (SWAPPED_OUT_BATTERY_ID)
        REFERENCES C##CAR.BATTERY (BATTERY_ID)
);
CREATE TABLE C##CAR.PERFORMANCES (
    PERFORMANCE_ID VARCHAR2(50) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    TOTAL_PERFORMANCE INT NOT NULL,
    SERVICE_COUNT INT DEFAULT 0,
    POSITIVE_RATING INT,
    CONSTRAINT FK_PERFORMANCES_STAFF FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES C##CAR.STAFF (EMPLOYEE_ID)
);
CREATE TABLE C##CAR.SWITCH_REQUESTS (
    SWITCH_REQUEST_ID VARCHAR2(50) PRIMARY KEY,
    VEHICLE_ID VARCHAR2(50) NOT NULL,
    SWITCH_MODE CHAR(1) CHECK (SWITCH_MODE IN ('D', 'L')),
    REQUEST_TIME TIMESTAMP NOT NULL,
    REMARKS VARCHAR2(255),
    CONSTRAINT FK_SWITCH_REQUESTS_VEHICLES FOREIGN KEY (VEHICLE_ID)
        REFERENCES C##CAR.VEHICLES (VEHICLE_ID),
    CONSTRAINT FK_SWITCH_REQUESTS_ACCEPTANCE_OF_SWITCH_REQUESTS FOREIGN KEY (SWITCH_REQUEST_ID)
        REFERENCES C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS (SWITCH_REQUEST_ID)
);
CREATE TABLE C##CAR.MAINTENANCE_ITEMS (
    MAINTENANCE_ITEM_ID VARCHAR2(50) PRIMARY KEY,
    VEHICLE_ID VARCHAR2(50) NOT NULL,
    MAINTENANCE_LOCATION VARCHAR2(50) UNIQUE,
    REMARKS VARCHAR2(255),
    SERVICE_TIME TIMESTAMP NOT NULL,
    ORDER_SUBMISSION_TIME TIMESTAMP,
    ORDER_STATUS CHAR(1) DEFAULT '0',
    EVALUATIONS VARCHAR2(255),
    CONSTRAINT FK_MAINTENANCE_ITEMS_VEHICLE FOREIGN KEY (VEHICLE_ID)
        REFERENCES C##CAR.VEHICLES (VEHICLE_ID)
);
CREATE TABLE C##CAR.VEHICLES (
    VEHICLE_ID VARCHAR2(50) PRIMARY KEY,
    VEHICLE_MODEL VARCHAR2(50) NOT NULL,
    OWNER_ID VARCHAR2(50) NOT NULL,
    PURCHASE_DATE TIMESTAMP NOT NULL,
    BATTERY_ID VARCHAR2(50) DEFAULT NULL,
    CONSTRAINT FK_VEHICLES_OWNER FOREIGN KEY (OWNER_ID)
        REFERENCES C##CAR.OWNERS (OWNER_ID),
    CONSTRAINT FK_VEHICLES_VEHICLE_PARAMETERS FOREIGN KEY (VEHICLE_MODEL)
        REFERENCES C##CAR.VEHICLE_PARAMETERS (VEHICLE_MODEL),
    CONSTRAINT FK_VEHICLES_BATTERY FOREIGN KEY (BATTERY_ID)
        REFERENCES C##CAR.BATTERY (BATTERY_ID)
);
CREATE TABLE C##CAR.STAFF_IN_SWITCH_STATIONS (
    EMPLOYEE_ID VARCHAR2(50) PRIMARY KEY,
    SWITCH_STATION_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_STAFF_IN_SWITCH_STATIONS_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES C##CAR.STAFF (EMPLOYEE_ID),
    CONSTRAINT FK_STAFF_IN_SWITCH_STATIONS_SWITCH_STATIONS FOREIGN KEY (SWITCH_STATION_ID)
        REFERENCES C##CAR.SWITCH_STATIONS (SWITCH_STATION_ID)
);
CREATE TABLE C##CAR.COMPLETION_OF_MAINTENANCE (
    MAINTENANCE_ITEM_ID VARCHAR2(50) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_COMPLETION_OF_MAINTENANCE_STAFF FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES C##CAR.STAFF (EMPLOYEE_ID),
    CONSTRAINT FK_COMPLETION_OF_MAINTENANCE_MAINTENANCE_ITEMS FOREIGN KEY (MAINTENANCE_ITEM_ID)
        REFERENCES C##CAR.MAINTENANCE_ITEMS (MAINTENANCE_ITEM_ID)
);
CREATE TABLE C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS (
    SWITCH_REQUEST_ID VARCHAR2(50) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ACCEPTANCE_OF_SWITCH_REQUESTS_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES C##CAR.STAFF (EMPLOYEE_ID)
);